# Конфигурация плагина RatingPlugin

reward:
  max-level: 5                 # Максимальный уровень награды
  allow-repeated-rating: false  # Разрешить повторное оценивание одного и того же игрока (true/false)
  sound:
    praise: "ENTITY_PLAYER_LEVELUP" # Звук, когда игрока похвалили
    sender: "ENTITY_PLAYER_LEVELUP"  # Звук, когда отправитель получает подтверждение
  levels:
    level-1:
      threshold: 10             # Порог рейтинга для уровня 1
      type: "money"             # Тип приза (money, item, command)
      amount: 10                # Количество денег
    level-2:
      threshold: 20             # Порог рейтинга для уровня 2
      type: "item"              # Тип приза
      item: "DIAMOND"           # Предмет, который игрок получит
      amount: 1                 # Количество предметов
    level-3:
      threshold: 30             # Порог рейтинга для уровня 3
      type: "command"           # Тип приза
      command: "give {player} diamond 1" # Команда, которая будет выполнена
    level-4:
      threshold: 40             # Порог рейтинга для уровня 4
      type: "money"             # Тип приза
      amount: 20                # Количество денег
    level-5:
      threshold: 50             # Порог рейтинга для уровня 5
      type: "item"              # Тип приза
      item: "GOLD_INGOT"        # Предмет, который игрок получит
      amount: 5                 # Количество предметов