# Конфигурация плагина RatingPlugin

# Сообщения, используемые в плагине
messages:
  notPlayer: "&cЭта команда доступна только игрокам."
  noPermission: "&eУ вас нет прав для использования этой команды."
  usage: "&7Используйте: /rate <игрок>"
  playerNotFound: "&cИгрок не найден."
  selfRating: "&6Вы не можете оценивать самого себя."
  alreadyRated: "&aВы уже оценили {player}. Вы больше не можете его оценивать."
  ratingCooldown: "&eВы не можете оценивать {player} снова так быстро. Подождите 60 секунд."
  rewardMessage: "&aВы оценили {player}. Он получил {amount} монет!"
  praise: "&bВас похвалили! Теперь у вас {rating} очков рейтинга и уровень награды {level}!"
  maxRewardLevel: "&c{player} уже достиг максимального уровня награды."
  invalidPrizeType: "&cНеправильный тип приза."
  ratingInfo: "&7{player}, ваш текущий рейтинг: {rating}."

# Настройки наград
reward:
  threshold: 20 # Порог для получения награды
  max-level: 5  # Максимальный уровень награды
  increment: 10  # Увеличение награды

# Призы для уровней наград
reward:
  levels:
    level-1:
      type: "money"
      amount: 10
    level-2:
      type: "item"
      item: "DIAMOND"
      amount: 1
    level-3:
      type: "command"
      command: "give {player} DIAMOND 1"
    level-4:
      type: "money"
      amount: 20
    level-5:
      type: "item"
      item: "GOLD_INGOT"
      amount: 5

# Данные игроков
players: {}